services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  node-server:
    build:
      context: ./my-express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./my-express-server/src:/usr/src/app/src
    command: yarn start
